stages:
- build
- publish

cc7:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - yum install -y git rpm-build
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

slc6:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/slc6-base
  script:
    - yum install -y git rpm-build python-argparse tar
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

ubuntu-artful:
  stage: build
  image: ubuntu:artful
  script:
    - ci/debian/prepare.sh
    - packaging/make-deb.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r build/debian-build-arena/*.{deb,ddeb,dsc} ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

debian-jessie:
  stage: build
  image: debian:jessie
  script:
    - ci/debian/prepare.sh
    - packaging/make-deb.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r build/debian-build-arena/*.{deb,dsc} ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"


docs:
  stage: publish
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - yum install -y git rpm-build python-argparse tar cmake python2-sphinx make
    - packaging/make-docs.sh
  tags:
    - docker-cc7
  artifacts:
    paths:
    - build
