stages:
- build

cc7:
  stage: build
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - yum install -y git rpm-build
    - packaging/gitlab-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"
